### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by aniruddhha** [abdlquadri/vertx-eventbus-java#2]
There is issue, some classes and properties are missing, will you please push proper code. @abdlquadri

**Comment by abdlquadri** [comment]
Kindly confirm. Thanks

**Comment by aniruddhha** [comment]
No still there is build failed. Kindly check logs

aniruddha@aniruddha-Inspiron-5559:~/Desktop/vertx-java$ git clone https://github.com/abdlquadri/vertx-eventbus-java.git
Cloning into 'vertx-eventbus-java'...
remote: Counting objects: 177, done.
remote: Total 177 (delta 0), reused 0 (delta 0), pack-reused 177
Receiving objects: 100% (177/177), 71.15 KiB | 0 bytes/s, done.
Resolving deltas: 100% (67/67), done.
Checking connectivity... done.
aniruddha@aniruddha-Inspiron-5559:~/Desktop/vertx-java$ cd vertx-eventbus-java/
aniruddha@aniruddha-Inspiron-5559:~/Desktop/vertx-java/vertx-eventbus-java$ ./gradlew build
:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.5
warning: [options] source value 1.5 is obsolete and will be removed in a future release
warning: [options] target value 1.5 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
/home/aniruddha/Desktop/vertx-java/vertx-eventbus-java/src/main/java/ng/abdlquadri/eventbus/EventBus.java:34: error: cannot find symbol
  public static final ConcurrentMap<String, List<Handler>> handlers = new ConcurrentHashMap<String, List<Handler>>();
                      ^
  symbol:   class ConcurrentMap
  location: class EventBus
/home/aniruddha/Desktop/vertx-java/vertx-eventbus-java/src/main/java/ng/abdlquadri/eventbus/EventBus.java:35: error: cannot find symbol
  public static final ConcurrentMap<String, Handler> replyHandlers = new ConcurrentHashMap<String, Handler>();
                      ^
  symbol:   class ConcurrentMap
  location: class EventBus
/home/aniruddha/Desktop/vertx-java/vertx-eventbus-java/src/main/java/ng/abdlquadri/eventbus/EventBus.java:202: error: cannot assign a value to final variable channel
          channel = future.channel();
          ^
3 errors
4 warnings
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.986 secs
aniruddha@aniruddha-Inspiron-5559:~/Desktop/vertx-java/vertx-eventbus-java$

**Comment by abdlquadri** [comment]
Sorry for the inconveniences. Please try now. Lets hope git and idea will agree this time around.

Please use `./gradlew jar`. The tests have issues.

Cheers.

**Comment by aniruddhha** [comment]
Thanks now its working ..

**Comment by abdlquadri** [comment]
UWC. Thanks for reaching out. Please let me if you have further questions.
